require 'minitest/spec'
require 'minitest/autorun'
require_relative '../lib/access_query.rb'
require_relative '../lib/resource.rb'
require_relative '../lib/resource_user.rb'
require_relative '../lib/resource_queries.rb'
